### ISSUE TITLE
[Bug] Download error: Data count not equal to block size.

### ISSUE THREAD

**Issue by hollow-pigeon** [DJDoubleD/QobuzDownloaderX-MOD#118]
> Unknown error during Track Download.
> TagLib.CorruptFileException: Data count not equal to block size.
>    at TagLib.Flac.Block..ctor(BlockHeader header, ByteVector data) in C:\code\taglib-sharp\src\TaglibSharp\Flac\Block.cs:line 72
>    at TagLib.Flac.File.ReadBlocks(Int64& start, Int64& end, BlockMode mode, BlockType[] types) in C:\code\taglib-sharp\src\TaglibSharp\Flac\File.cs:line 505
>    at TagLib.Flac.File.Save() in C:\code\taglib-sharp\src\TaglibSharp\Flac\File.cs:line 200
>    at QobuzDownloaderX.Shared.AudioFileTagger.AddMetaDataTags(DownloadItemInfo fileInfo, String tagFilePath, String tagCoverArtFilePath, DownloadLogger logger) in D:\a\QobuzDownloaderX-MOD\QobuzDownloaderX-MOD\QobuzDownloaderX\Shared\Tools\AudioFileTagger.cs:line 302
>    at QobuzDownloaderX.Shared.DownloadManager.<DownloadTrackAsync>d__28.MoveNext() in D:\a\QobuzDownloaderX-MOD\QobuzDownloaderX-MOD\QobuzDownloaderX\Shared\DownloadManager.cs:line 273

UK account, happens with this specific album: https://play.qobuz.com/album/an9edjravnlgb. Album link grabbed using in-app search, in-app search works good with another albums. It does download files, but i can't open them (player says they're corrupted, even those from this album that downloaded without error)

Not that big of a deal for me, post more for you to know. but it'll be cool if you could solve this

**Comment by orbittwz** [comment]
![Image](https://github.com/user-attachments/assets/05719a92-4194-4c07-8bf0-72c5553fc629)

Looks OK here...
What did you do that caused this error?

**Comment by hollow-pigeon** [comment]
i can't remember, i thought log will help you. as i said, doesn't really matter for me. i published it more for you (a developer)

**Comment by orbittwz** [comment]
if you don't want this please close the issue, the author has a lot to handle

**Comment by hollow-pigeon** [comment]
ok, I'm sorry. I'm new here
