### ISSUE TITLE
[Feature Request] Support Long Paths (>260 characters)

### ISSUE THREAD

**Issue by DJDoubleD** [DJDoubleD/QobuzDownloaderX-MOD#56]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**
When downloading tracks for which the total path length exceeds the [Windows maximum of 260 characters](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry), the following error occurs:

```
Unknown error during Track Download.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'Z:\qobuz\- Labels\Argon Verlag\Rebecca Yarros\The things we leave unfinished - Eine Familie. Zwei Geschichten. Tausend Gefühle. (Ungekürzte Lesung [up152nh72omda]\MP3\185 - Kapitel 185 - The things we leave unfinished - Eine Familie. Zwei Geschichten. Tausend Gefühle.mp3'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at QobuzDownloaderX.Shared.DownloadManager.<DownloadFileAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at QobuzDownloaderX.Shared.DownloadManager.<DownloadTrackAsync>d__28.MoveNext()
```

---

## **Describe the solution you'd like**
Support longer paths, if [enabled on Windows 10, Version 1607, and Later](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later)

---

### **Additional context**
An example long track which will give problems if downloaded as part of a label in nested folders:
[Kapitel 185 - The things we leave unfinished - Eine Familie. Zwei Geschichten. Tausend Gefühle](https://play.qobuz.com/album/up152nh72omda?track=220613370)

**Comment by DJDoubleD** [comment]
Solution will still require users to [Enable Long Paths in Windows 10 (Version 1607 and Later)](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#enable-long-paths-in-windows-10-version-1607-and-later)

Will need to add this to the release notes and attach the zipped .reg file to the release (GitHub doesn't allow .ref attachments).
Alternative Powershell command:
```Powershell
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
-Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
```
[EnableLongPaths.zip](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/files/12909806/EnableLongPaths.zip)
