### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Feather-fall** [DJDoubleD/QobuzDownloaderX-MOD#65]
I can't log in via either qobuzdownloader or qobuz-dl since 2 days ago.
Perhaps Qobuz log-in API is changed? Help me pls.

**Comment by orbittwz** [comment]
seems OK here, did you tried log in to the site via browser and see if there is a problem?

**Comment by Feather-fall** [comment]
I can log in via play.qobuz.com. Qobuz apps work fine. The problem is I can't log in via Qobuzdownloader or Qobuz-dl.
Qobuzdownloader says "Unknown error initiating API connection. Error" after I enter the email/password or id/token.
Here's the login error detail:

System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 162.125.2.5:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at QobuzApiSharp.Service.QobuzApiHelper.FetchBundleString()
   at QobuzApiSharp.Service.QobuzApiHelper.GetWebPlayerAppSecret()
   at QobuzApiSharp.Service.QobuzApiService..ctor(String appId, String appSecret, Boolean useWebPlayerAppIdAndSecret)
   at QobuzDownloaderX.Shared.QobuzApiServiceManager.Initialize() in D:\a\QobuzDownloaderX-MOD\QobuzDownloaderX-MOD\QobuzDownloaderX\Shared\QobuzApiServiceManager.cs:line 29
   at QobuzDownloaderX.LoginForm.LoginBG_DoWork(Object sender, DoWorkEventArgs e) in D:\a\QobuzDownloaderX-MOD\QobuzDownloaderX-MOD\QobuzDownloaderX\View\LoginForm.cs:line 305

**Comment by orbittwz** [comment]
I'm not sure about this error, I can only suggest making sure your FW is allowing traffic with the program, or maybe you wrote the credentials with unsupported characters?
In any case, the author will see this later, thanks

**Comment by DJDoubleD** [comment]
> I can log in via play.qobuz.com. Qobuz apps work fine. The problem is I can't log in via Qobuzdownloader or Qobuz-dl. Qobuzdownloader says "Unknown error initiating API connection. Error" after I enter the email/password or id/token. Here's the login error detail:
> 
> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 162.125.2.5:443
>...

If google translate is to be believed, that error message implies that the Qobuz servers didn't respond or timed out when trying to get the "bundle string". This is the big javascript file that contains the sources to their web player and it's ClientID & ClientSecret, which QBDLX-MOD needs in order to login, search, download, ...
The current link to the bundje.js (at time of writing this) is [this one](https://play.qobuz.com/resources/7.1.3-b011/bundle.js)

Could you please do some tests:
- Can you download the bundle.js file from the link I mentioned above? If so, how long does it take to download?
- You say that you can use the webplayer at play.qobuz.com. Does this also work for you in a private browsing window? (Maybe your web player only still works in a normal browser window because it cached the bundle.js at an earlier time)

It seems some people do have problems where loading the bundle.js file in the background times out or just hangs.
This is due to local network issues which most likely can't be solved in the software (you say you are getting the same result with qobuz-dl, which does the same thing with the bundle.js file but in python).
As is mentioned in the disclaimer of my readme file, QBDLX-MOD doesn't save or contain any ClientID's or Secrets, they are fetched in real time from the web player. So this is a deliberate choice to avoid any legal implications.

**Comment by Feather-fall** [comment]
Thank you for reminding me. I switched to vpn, and everything worked out.
It's just weird that I'd been using qobuz-dl for almost a year without incident, so at first I just couldn't believe it's because of the network.
