### ISSUE TITLE
[Bug] Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by apellier** [DJDoubleD/QobuzDownloaderX-MOD#87]
# **🐞 Bug Report**

## **Describe the bug**

* Hello, this is the first time I am using the tool and on launch I get an error : "Object reference not set to an instance of an object" from the .NET Framework tool. I can still continue to the download window but when I try to download anything I get an error.
* 
---

### **Is this a regression?**
 
As I have not use the tool yet, I can't say it's a regression.

---

### **To Reproduce**

1. Launch the .exe 
2. Login with credentials
3. Authentification is cleared, then a window  pops up with the error message
4. Click on "Continue"
5. Search a track or paste  the track URL
6. Click on Download
7. Get error message + track is not downloaded

---

### **Expected behaviour**

* No error pop up should be displayed and download should proceed normally

---

### **Screenshots**

![image](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/119315881/c73dd0fc-ab9c-450d-bc68-80774190dc9a)
![image](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/119315881/21762518-2345-451f-9736-72e0a0a47f7a)

---

[Download_Errors.log](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/files/15340103/Download_Errors.log)

*

**Comment by DJDoubleD** [comment]
@apellier I have a few additional questions in order to hopefully better be able to investigate and solve this issue:

1. What OS are you running (I can only test Windows 10 atm)?
2. Can you make sure that you have the [.net 4.8 framework](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer) installed?
3. You say you get the error pop-up right after login. In the error window from your screenshot, there is a text area at the bottom with a very long error log. Could you please copy that entire error message, paste it in a txt file and add that file to this issue? I can't see the entire message just from the screenshot and text is easier...

**Comment by xdjohn99** [comment]
> @apellier I have a few additional questions in order to hopefully better be able to investigate and solve this issue:
> 
> 1. What OS are you running (I can only test Windows 10 atm)?
> 2. Can you make sure that you have the [.net 4.8 framework](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer) installed?
> 3. You say you get the error pop-up right after login. In the error window from your screenshot, there is a text area at the bottom with a very long error log. Could you please copy that entire error message, paste it in a txt file and add that file to this issue? I can't see the entire message just from the screenshot and text is easier...

I have the same issue. It started happening a few days ago, after Windows 10 automatically updated the system. (In terms of timing, that's how it happened, but I'm not sure if the two are related.)

1. WIN 10 22H2

2. Installed

3. Here:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.QobuzDownloaderX.MainForm_Load(Object sender, EventArgs e) in D:\a\QobuzDownloaderX-MOD\QobuzDownloaderX-MOD\QobuzDownloaderX\View\MainForm.cs:line 74
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
QobuzDownloaderX
    Assembly Version: 1.2.5.0
    Win32 Version: 1.2.5.0
    CodeBase: file:///E:/QBDLX-MOD_1.2.5.0/QobuzDownloaderX.exe
----------------------------------------
PortableJsonSettingsProvider
    Assembly Version: 0.2.2.0
    Win32 Version: 0.2.2.0
    CodeBase: file:///E:/QBDLX-MOD_1.2.5.0/PortableJsonSettingsProvider.DLL
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9236.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///E:/QBDLX-MOD_1.2.5.0/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
QobuzApiSharp
    Assembly Version: 0.0.7.0
    Win32 Version: 0.0.7.0
    CodeBase: file:///E:/QBDLX-MOD_1.2.5.0/QobuzApiSharp.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by xdjohn99** [comment]
Additionally. The search function is still available but it cannot download.

**Comment by xdjohn99** [comment]
1. Yes, every time
2. I tried version 1.2.4.0, same problem
3. It still doesn't work. When I discovered this issue a couple of days ago, I reinstalled it immediately through [.net framework](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer)

**Comment by DJDoubleD** [comment]
Additional report from another user for which the application crashed with the same error dialog.

Download error logged the following:
```
Album Download Task ERROR.
System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.Models.DownloadItemInfo.SetAlbumCoverArtUrls(Album qobuzAlbum) in D:\a\QobuzDownloaderX-MOD\QobuzDownloaderX-MOD\QobuzDownloaderX\Models\Download\DownloadItemInfo.cs:line 117
   at QobuzDownloaderX.Models.DownloadItemInfo.SetAlbumDownloadInfo(Album qobuzAlbum) in D:\a\QobuzDownloaderX-MOD\QobuzDownloaderX-MOD\QobuzDownloaderX\Models\Download\DownloadItemInfo.cs:line 62
   at QobuzDownloaderX.Shared.DownloadManager.<DownloadAlbumAsync>d__29.MoveNext() in D:\a\QobuzDownloaderX-MOD\QobuzDownloaderX-MOD\QobuzDownloaderX\Shared\DownloadManager.cs:line 321
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at QobuzDownloaderX.Shared.DownloadManager.<StartDownloadAlbumTaskAsync>d__37.MoveNext() in D:\a\QobuzDownloaderX-MOD\QobuzDownloaderX-MOD\QobuzDownloaderX\Shared\DownloadManager.cs:line 700
```

Example links use:
https://open.qobuz.com/album/ezdz7pij8bfnc
https://open.qobuz.com/album/bkc52ysua8l9b

**Comment by Le-Papu** [comment]
same problem here

**Comment by HandsomeTopKhi** [comment]
@apellier, @Le-Papu & @xdjohn99 just change the user id and token. This issue arises from an expired account try here (https://rentry.co/firehawk52#qobuz-tokens) to get another id/token and this will go away. If you still get it with another id/token choose another one. This issues only happens if the account you using has expired.
